[aws]
aws_access_key = 
aws_secret_key = 
aws_region = eu-north-1
aws_bucket_name = ecommerce-data-platform-dedi

[file_path]
input_path = 's3://ecommerce-data-platform-dedi/Input_Data/'

[file_names]
customers = customers.csv
orders = orders.csv
payments = payments.csv
products = products.csv

[bronze_path]
bronze = 's3://ecommerce-data-platform-dedi/bronze/'

[silver_path]
silver = 's3://ecommerce-data-platform-dedi/silver/'

[gold_path]

gold = 's3://ecommerce-data-platform-dedi/gold/'





